DATABASE_URL = "postgresql://mmd:mmd_pass@localhost:5432/mmd_db"
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "mmd_pass123"
REDIS_URL = "redis://localhost:6379/0"

TICKERS = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ADANIENT.NS"]
TICKER_DISPLAY = {
    "RELIANCE.NS": "RELIANCE", "TCS.NS": "TCS", "INFY.NS": "INFY",
    "HDFCBANK.NS": "HDFCBANK", "ADANIENT.NS": "ADANIENT"
}

TWELVE_DATA_API_KEY = "d4a56d97799847eaa14df793cc491915"
TWELVE_DATA_SYMBOLS = {
    "RELIANCE.NS": "RELIANCE.NS", "TCS.NS": "TCS.NS", "INFY.NS": "INFY.NS",
    "HDFCBANK.NS": "HDFCBANK.NS", "ADANIENT.NS": "ADANIENT.NS"
}